package com.pidevv;


import com.codename1.io.ConnectionRequest;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.mycompany.gui.AjoutCoachingForm;
import com.mycompany.gui.AjoutReclamationForm;
import com.mycompany.gui.ListCoachingForm;
import com.mycompany.gui.ListeRdvForm;
import com.mycompany.gui.MapForm;
import com.mycompany.gui.ModifierCoachingForm;
import com.mycompany.gui.SignInForm;
import com.mycompany.gui.SignUpForm;
import com.mycompany.gui.StatistiqueForm;
import com.mycompany.gui.StatistiquePieForm;
import com.mycompany.gui.frontC;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;
    ConnectionRequest con;
    String url = "http://127.0.0.1:8000/afficherjson";

    Form hi;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){    
            current.show();
            return;
        }
        //houni awl interface yet7al
        //new MapForm(); //n7oto signup bch yjibha awl form
       // new SignInForm(theme).show();
     // new AjoutCoachingForm(theme).show();
  //new ListCoachingForm(theme).show();
              //  new rechercheForm(theme).show();

     //  new ModifierCoachingForm(theme).show();
 /*HomeCoachingForm home=new HomeCoachingForm();
     home.show();*/
 //new StatistiqueForm(theme).show();
   new frontC(theme).show();

    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
